### ISSUE TITLE
[Fix] 0820 피드백 반영 

### ISSUE THREAD

**Issue by pcsoyeon** [pcsoyeon/SSAC-Weather#6]
## TO-DO
- [x] 데이터 response 모델 codingkey 삭제
- [x] 네트워크 상태코드 enum으로 관리
- [ ] 네트워크 오류 Error 프로토콜 채택
- [ ] 온도 데이터 연산 프로퍼티 활용
